//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiExpressV3.datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENTO_TRIBUTARIO
    {
        public decimal ID_DOCUMENTO_TRIB { get; set; }
        public Nullable<System.DateTime> FECHA_DE_CREACION { get; set; }
        public decimal ID_TIPO_DOC { get; set; }
        public decimal ID_SERVICIO { get; set; }
        public string RUT_USUARIO_VEND { get; set; }
        public decimal ID_FORMA_PAGO { get; set; }
        public string NOMBRE_CLIENTE { get; set; }
        public string RUT_CLIENTE { get; set; }
        public decimal TOTAL_PAGAR { get; set; }
    
        public virtual SERVICIO SERVICIO { get; set; }
        public virtual FORMA_PAGO FORMA_PAGO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual TIPO_DOCUMENTO TIPO_DOCUMENTO { get; set; }
    }
}
