//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiExpressV3.datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADO_ORDEN_COMPRA
    {
        public ESTADO_ORDEN_COMPRA()
        {
            this.ORDEN_DE_COMPRA = new HashSet<ORDEN_DE_COMPRA>();
        }
    
        public decimal ID_ESTADO_ORDEN { get; set; }
        public string DESCRIPCION_ESTADO { get; set; }
    
        public virtual ICollection<ORDEN_DE_COMPRA> ORDEN_DE_COMPRA { get; set; }
    }
}
