//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiExpressV3.datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAMILIA_PRODUCTO
    {
        public FAMILIA_PRODUCTO()
        {
            this.TIPO_PRODUCTO = new HashSet<TIPO_PRODUCTO>();
        }
    
        public decimal ID_FAMILIA_PRODUCTO { get; set; }
        public string DESCRIPCION_FAMILIA_PROD { get; set; }
    
        public virtual ICollection<TIPO_PRODUCTO> TIPO_PRODUCTO { get; set; }
    }
}
