//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiExpressV3.datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORMA_PAGO
    {
        public FORMA_PAGO()
        {
            this.DOCUMENTO_TRIBUTARIO = new HashSet<DOCUMENTO_TRIBUTARIO>();
        }
    
        public decimal ID_FORMA { get; set; }
        public string NOMBRE_FORMA { get; set; }
    
        public virtual ICollection<DOCUMENTO_TRIBUTARIO> DOCUMENTO_TRIBUTARIO { get; set; }
    }
}
