//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiExpressV3.datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN_DE_COMPRA
    {
        public ORDEN_DE_COMPRA()
        {
            this.RECEPCION = new HashSet<RECEPCION>();
        }
    
        public decimal ID_ORDEN { get; set; }
        public string RUT_USUARIO { get; set; }
        public decimal ID_PRODUCTO { get; set; }
        public System.DateTime FECHA_DE_CREACION { get; set; }
        public decimal ID_ESTADO_ORDEN { get; set; }
        public decimal MONTO { get; set; }
    
        public virtual ESTADO_ORDEN_COMPRA ESTADO_ORDEN_COMPRA { get; set; }
        public virtual ICollection<RECEPCION> RECEPCION { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual PRODUCTOS PRODUCTOS { get; set; }
    }
}
