//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiExpressV3.datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEEDOR
    {
        public PROVEEDOR()
        {
            this.PRODUCTOS = new HashSet<PRODUCTOS>();
        }
    
        public decimal ID_PROVEEDOR { get; set; }
        public string RUT_EMPRESA { get; set; }
        public string RAZON_SOCIAL { get; set; }
        public string DIRECCION { get; set; }
        public decimal ID_RUBRO { get; set; }
        public string TELEFONO_CONTACTO { get; set; }
        public string CORREO_CONTACTO { get; set; }
    
        public virtual ICollection<PRODUCTOS> PRODUCTOS { get; set; }
        public virtual RUBRO RUBRO { get; set; }
    }
}
