//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiExpressV3.datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEPCION
    {
        public decimal ID_RECEPCION { get; set; }
        public string RUT_USUARIO { get; set; }
        public Nullable<System.DateTime> FECHA_RECEPCION { get; set; }
        public string OBSERVACIONES { get; set; }
        public decimal ID_ORDEN_COMPRA { get; set; }
    
        public virtual ORDEN_DE_COMPRA ORDEN_DE_COMPRA { get; set; }
    }
}
