//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiExpressV3.datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIO
    {
        public SERVICIO()
        {
            this.DOCUMENTO_TRIBUTARIO = new HashSet<DOCUMENTO_TRIBUTARIO>();
        }
    
        public decimal ID_SERVICIO { get; set; }
        public string RUT_USUARIO { get; set; }
        public string NOM_AP_USUARIO { get; set; }
        public string PATENTE_VEHICULO { get; set; }
        public decimal ID_TIPO_SERVICIO { get; set; }
        public decimal ID_PROD_VENTA { get; set; }
        public string RUT_MECANICO { get; set; }
        public string NOMBRE_MECANICO { get; set; }
        public Nullable<decimal> CODIGO_PRODUCTO { get; set; }
    
        public virtual ICollection<DOCUMENTO_TRIBUTARIO> DOCUMENTO_TRIBUTARIO { get; set; }
        public virtual VEHICULOS VEHICULOS { get; set; }
        public virtual TIPO_SERVICIO TIPO_SERVICIO { get; set; }
        public virtual VENTA_PRODUCTO VENTA_PRODUCTO { get; set; }
    }
}
