//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiExpressV3.datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class ServiExpressEntities : DbContext
    {
        public ServiExpressEntities()
            : base("name=ServiExpressEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DOCUMENTO_TRIBUTARIO> DOCUMENTO_TRIBUTARIO { get; set; }
        public DbSet<ESTADO_ORDEN_COMPRA> ESTADO_ORDEN_COMPRA { get; set; }
        public DbSet<FAMILIA_PRODUCTO> FAMILIA_PRODUCTO { get; set; }
        public DbSet<FORMA_PAGO> FORMA_PAGO { get; set; }
        public DbSet<OPERACIONES> OPERACIONES { get; set; }
        public DbSet<ORDEN_DE_COMPRA> ORDEN_DE_COMPRA { get; set; }
        public DbSet<PRODUCTOS> PRODUCTOS { get; set; }
        public DbSet<PROVEEDOR> PROVEEDOR { get; set; }
        public DbSet<RECEPCION> RECEPCION { get; set; }
        public DbSet<RESERVAS> RESERVAS { get; set; }
        public DbSet<ROL_OPERACION> ROL_OPERACION { get; set; }
        public DbSet<ROL_USUARIO> ROL_USUARIO { get; set; }
        public DbSet<RUBRO> RUBRO { get; set; }
        public DbSet<SERVICIO> SERVICIO { get; set; }
        public DbSet<TIPO_DOCUMENTO> TIPO_DOCUMENTO { get; set; }
        public DbSet<TIPO_PRODUCTO> TIPO_PRODUCTO { get; set; }
        public DbSet<TIPO_SERVICIO> TIPO_SERVICIO { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
        public DbSet<VEHICULOS> VEHICULOS { get; set; }
        public DbSet<VENTA_PRODUCTO> VENTA_PRODUCTO { get; set; }
    
        public virtual int SP_CREATE_DOCTRIB(Nullable<System.DateTime> v_FECHACREA, Nullable<decimal> v_IDTIPODOC, Nullable<decimal> v_IDSERVICIO, string v_RUTUSUARIO, Nullable<decimal> v_IDFORMAPAGO, string v_NOMCLIENTE, string v_RUTCLIENTE, Nullable<decimal> v_TOTALPAGAR)
        {
            var v_FECHACREAParameter = v_FECHACREA.HasValue ?
                new ObjectParameter("V_FECHACREA", v_FECHACREA) :
                new ObjectParameter("V_FECHACREA", typeof(System.DateTime));
    
            var v_IDTIPODOCParameter = v_IDTIPODOC.HasValue ?
                new ObjectParameter("V_IDTIPODOC", v_IDTIPODOC) :
                new ObjectParameter("V_IDTIPODOC", typeof(decimal));
    
            var v_IDSERVICIOParameter = v_IDSERVICIO.HasValue ?
                new ObjectParameter("V_IDSERVICIO", v_IDSERVICIO) :
                new ObjectParameter("V_IDSERVICIO", typeof(decimal));
    
            var v_RUTUSUARIOParameter = v_RUTUSUARIO != null ?
                new ObjectParameter("V_RUTUSUARIO", v_RUTUSUARIO) :
                new ObjectParameter("V_RUTUSUARIO", typeof(string));
    
            var v_IDFORMAPAGOParameter = v_IDFORMAPAGO.HasValue ?
                new ObjectParameter("V_IDFORMAPAGO", v_IDFORMAPAGO) :
                new ObjectParameter("V_IDFORMAPAGO", typeof(decimal));
    
            var v_NOMCLIENTEParameter = v_NOMCLIENTE != null ?
                new ObjectParameter("V_NOMCLIENTE", v_NOMCLIENTE) :
                new ObjectParameter("V_NOMCLIENTE", typeof(string));
    
            var v_RUTCLIENTEParameter = v_RUTCLIENTE != null ?
                new ObjectParameter("V_RUTCLIENTE", v_RUTCLIENTE) :
                new ObjectParameter("V_RUTCLIENTE", typeof(string));
    
            var v_TOTALPAGARParameter = v_TOTALPAGAR.HasValue ?
                new ObjectParameter("V_TOTALPAGAR", v_TOTALPAGAR) :
                new ObjectParameter("V_TOTALPAGAR", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_DOCTRIB", v_FECHACREAParameter, v_IDTIPODOCParameter, v_IDSERVICIOParameter, v_RUTUSUARIOParameter, v_IDFORMAPAGOParameter, v_NOMCLIENTEParameter, v_RUTCLIENTEParameter, v_TOTALPAGARParameter);
        }
    
        public virtual int SP_CREATE_ODC(string v_RUTUSUARIO, Nullable<decimal> v_IDPRODUCTO, Nullable<System.DateTime> v_FECHACREACION, Nullable<decimal> v_IDESTADOORDEN, Nullable<decimal> v_MONTO)
        {
            var v_RUTUSUARIOParameter = v_RUTUSUARIO != null ?
                new ObjectParameter("V_RUTUSUARIO", v_RUTUSUARIO) :
                new ObjectParameter("V_RUTUSUARIO", typeof(string));
    
            var v_IDPRODUCTOParameter = v_IDPRODUCTO.HasValue ?
                new ObjectParameter("V_IDPRODUCTO", v_IDPRODUCTO) :
                new ObjectParameter("V_IDPRODUCTO", typeof(decimal));
    
            var v_FECHACREACIONParameter = v_FECHACREACION.HasValue ?
                new ObjectParameter("V_FECHACREACION", v_FECHACREACION) :
                new ObjectParameter("V_FECHACREACION", typeof(System.DateTime));
    
            var v_IDESTADOORDENParameter = v_IDESTADOORDEN.HasValue ?
                new ObjectParameter("V_IDESTADOORDEN", v_IDESTADOORDEN) :
                new ObjectParameter("V_IDESTADOORDEN", typeof(decimal));
    
            var v_MONTOParameter = v_MONTO.HasValue ?
                new ObjectParameter("V_MONTO", v_MONTO) :
                new ObjectParameter("V_MONTO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_ODC", v_RUTUSUARIOParameter, v_IDPRODUCTOParameter, v_FECHACREACIONParameter, v_IDESTADOORDENParameter, v_MONTOParameter);
        }
    
        public virtual int SP_CREATE_PRODUCTO(Nullable<decimal> v_CODPROD, Nullable<decimal> v_IDPROVEEDOR, Nullable<decimal> v_IDTIPOPROD, string v_NOMBREPROD, string v_MARCAPROD, string v_DESCPROD, Nullable<System.DateTime> v_FECHAVENC, Nullable<decimal> v_PRECIOVENTA, Nullable<decimal> v_PRECIOCOMPRA, Nullable<decimal> v_STOCK)
        {
            var v_CODPRODParameter = v_CODPROD.HasValue ?
                new ObjectParameter("V_CODPROD", v_CODPROD) :
                new ObjectParameter("V_CODPROD", typeof(decimal));
    
            var v_IDPROVEEDORParameter = v_IDPROVEEDOR.HasValue ?
                new ObjectParameter("V_IDPROVEEDOR", v_IDPROVEEDOR) :
                new ObjectParameter("V_IDPROVEEDOR", typeof(decimal));
    
            var v_IDTIPOPRODParameter = v_IDTIPOPROD.HasValue ?
                new ObjectParameter("V_IDTIPOPROD", v_IDTIPOPROD) :
                new ObjectParameter("V_IDTIPOPROD", typeof(decimal));
    
            var v_NOMBREPRODParameter = v_NOMBREPROD != null ?
                new ObjectParameter("V_NOMBREPROD", v_NOMBREPROD) :
                new ObjectParameter("V_NOMBREPROD", typeof(string));
    
            var v_MARCAPRODParameter = v_MARCAPROD != null ?
                new ObjectParameter("V_MARCAPROD", v_MARCAPROD) :
                new ObjectParameter("V_MARCAPROD", typeof(string));
    
            var v_DESCPRODParameter = v_DESCPROD != null ?
                new ObjectParameter("V_DESCPROD", v_DESCPROD) :
                new ObjectParameter("V_DESCPROD", typeof(string));
    
            var v_FECHAVENCParameter = v_FECHAVENC.HasValue ?
                new ObjectParameter("V_FECHAVENC", v_FECHAVENC) :
                new ObjectParameter("V_FECHAVENC", typeof(System.DateTime));
    
            var v_PRECIOVENTAParameter = v_PRECIOVENTA.HasValue ?
                new ObjectParameter("V_PRECIOVENTA", v_PRECIOVENTA) :
                new ObjectParameter("V_PRECIOVENTA", typeof(decimal));
    
            var v_PRECIOCOMPRAParameter = v_PRECIOCOMPRA.HasValue ?
                new ObjectParameter("V_PRECIOCOMPRA", v_PRECIOCOMPRA) :
                new ObjectParameter("V_PRECIOCOMPRA", typeof(decimal));
    
            var v_STOCKParameter = v_STOCK.HasValue ?
                new ObjectParameter("V_STOCK", v_STOCK) :
                new ObjectParameter("V_STOCK", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_PRODUCTO", v_CODPRODParameter, v_IDPROVEEDORParameter, v_IDTIPOPRODParameter, v_NOMBREPRODParameter, v_MARCAPRODParameter, v_DESCPRODParameter, v_FECHAVENCParameter, v_PRECIOVENTAParameter, v_PRECIOCOMPRAParameter, v_STOCKParameter);
        }
    
        public virtual int SP_CREATE_PROVEEDOR(string v_RUTEMPRESA, string v_RAZONSOCIAL, string v_DIRECCION, Nullable<decimal> v_IDRUBRO, string v_TELEFONOCONTACTO, string v_CORREOCONTACTO)
        {
            var v_RUTEMPRESAParameter = v_RUTEMPRESA != null ?
                new ObjectParameter("V_RUTEMPRESA", v_RUTEMPRESA) :
                new ObjectParameter("V_RUTEMPRESA", typeof(string));
    
            var v_RAZONSOCIALParameter = v_RAZONSOCIAL != null ?
                new ObjectParameter("V_RAZONSOCIAL", v_RAZONSOCIAL) :
                new ObjectParameter("V_RAZONSOCIAL", typeof(string));
    
            var v_DIRECCIONParameter = v_DIRECCION != null ?
                new ObjectParameter("V_DIRECCION", v_DIRECCION) :
                new ObjectParameter("V_DIRECCION", typeof(string));
    
            var v_IDRUBROParameter = v_IDRUBRO.HasValue ?
                new ObjectParameter("V_IDRUBRO", v_IDRUBRO) :
                new ObjectParameter("V_IDRUBRO", typeof(decimal));
    
            var v_TELEFONOCONTACTOParameter = v_TELEFONOCONTACTO != null ?
                new ObjectParameter("V_TELEFONOCONTACTO", v_TELEFONOCONTACTO) :
                new ObjectParameter("V_TELEFONOCONTACTO", typeof(string));
    
            var v_CORREOCONTACTOParameter = v_CORREOCONTACTO != null ?
                new ObjectParameter("V_CORREOCONTACTO", v_CORREOCONTACTO) :
                new ObjectParameter("V_CORREOCONTACTO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_PROVEEDOR", v_RUTEMPRESAParameter, v_RAZONSOCIALParameter, v_DIRECCIONParameter, v_IDRUBROParameter, v_TELEFONOCONTACTOParameter, v_CORREOCONTACTOParameter);
        }
    
        public virtual int SP_CREATE_RECEPCION(string v_RUTUSUARIO, Nullable<System.DateTime> v_FECHARECEP, string v_OBSERVACIONES, Nullable<decimal> v_IDORDENCOMPRA)
        {
            var v_RUTUSUARIOParameter = v_RUTUSUARIO != null ?
                new ObjectParameter("V_RUTUSUARIO", v_RUTUSUARIO) :
                new ObjectParameter("V_RUTUSUARIO", typeof(string));
    
            var v_FECHARECEPParameter = v_FECHARECEP.HasValue ?
                new ObjectParameter("V_FECHARECEP", v_FECHARECEP) :
                new ObjectParameter("V_FECHARECEP", typeof(System.DateTime));
    
            var v_OBSERVACIONESParameter = v_OBSERVACIONES != null ?
                new ObjectParameter("V_OBSERVACIONES", v_OBSERVACIONES) :
                new ObjectParameter("V_OBSERVACIONES", typeof(string));
    
            var v_IDORDENCOMPRAParameter = v_IDORDENCOMPRA.HasValue ?
                new ObjectParameter("V_IDORDENCOMPRA", v_IDORDENCOMPRA) :
                new ObjectParameter("V_IDORDENCOMPRA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_RECEPCION", v_RUTUSUARIOParameter, v_FECHARECEPParameter, v_OBSERVACIONESParameter, v_IDORDENCOMPRAParameter);
        }
    
        public virtual int SP_CREATE_RESERVAS(Nullable<System.DateTime> v_FECHARESERVA, string v_RUTUSUARIO, string v_NOMBRECLIE, string v_CORREOUSU, string v_PATENTE, Nullable<decimal> v_IDTIPOSERVICIO)
        {
            var v_FECHARESERVAParameter = v_FECHARESERVA.HasValue ?
                new ObjectParameter("V_FECHARESERVA", v_FECHARESERVA) :
                new ObjectParameter("V_FECHARESERVA", typeof(System.DateTime));
    
            var v_RUTUSUARIOParameter = v_RUTUSUARIO != null ?
                new ObjectParameter("V_RUTUSUARIO", v_RUTUSUARIO) :
                new ObjectParameter("V_RUTUSUARIO", typeof(string));
    
            var v_NOMBRECLIEParameter = v_NOMBRECLIE != null ?
                new ObjectParameter("V_NOMBRECLIE", v_NOMBRECLIE) :
                new ObjectParameter("V_NOMBRECLIE", typeof(string));
    
            var v_CORREOUSUParameter = v_CORREOUSU != null ?
                new ObjectParameter("V_CORREOUSU", v_CORREOUSU) :
                new ObjectParameter("V_CORREOUSU", typeof(string));
    
            var v_PATENTEParameter = v_PATENTE != null ?
                new ObjectParameter("V_PATENTE", v_PATENTE) :
                new ObjectParameter("V_PATENTE", typeof(string));
    
            var v_IDTIPOSERVICIOParameter = v_IDTIPOSERVICIO.HasValue ?
                new ObjectParameter("V_IDTIPOSERVICIO", v_IDTIPOSERVICIO) :
                new ObjectParameter("V_IDTIPOSERVICIO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_RESERVAS", v_FECHARESERVAParameter, v_RUTUSUARIOParameter, v_NOMBRECLIEParameter, v_CORREOUSUParameter, v_PATENTEParameter, v_IDTIPOSERVICIOParameter);
        }
    
        public virtual int SP_CREATE_RUBRO(string v_DESCRUBRO)
        {
            var v_DESCRUBROParameter = v_DESCRUBRO != null ?
                new ObjectParameter("V_DESCRUBRO", v_DESCRUBRO) :
                new ObjectParameter("V_DESCRUBRO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_RUBRO", v_DESCRUBROParameter);
        }
    
        public virtual int SP_CREATE_SERVICIO(string v_RUTUSUARIO, string v_NOMAPUSUARIO, string v_PATENTE, Nullable<decimal> v_IDTIPOSERV, Nullable<decimal> v_IDPRODVENT, string v_RUTMECANICO, string v_NOMMEC, Nullable<decimal> v_CODPRODUCTO)
        {
            var v_RUTUSUARIOParameter = v_RUTUSUARIO != null ?
                new ObjectParameter("V_RUTUSUARIO", v_RUTUSUARIO) :
                new ObjectParameter("V_RUTUSUARIO", typeof(string));
    
            var v_NOMAPUSUARIOParameter = v_NOMAPUSUARIO != null ?
                new ObjectParameter("V_NOMAPUSUARIO", v_NOMAPUSUARIO) :
                new ObjectParameter("V_NOMAPUSUARIO", typeof(string));
    
            var v_PATENTEParameter = v_PATENTE != null ?
                new ObjectParameter("V_PATENTE", v_PATENTE) :
                new ObjectParameter("V_PATENTE", typeof(string));
    
            var v_IDTIPOSERVParameter = v_IDTIPOSERV.HasValue ?
                new ObjectParameter("V_IDTIPOSERV", v_IDTIPOSERV) :
                new ObjectParameter("V_IDTIPOSERV", typeof(decimal));
    
            var v_IDPRODVENTParameter = v_IDPRODVENT.HasValue ?
                new ObjectParameter("V_IDPRODVENT", v_IDPRODVENT) :
                new ObjectParameter("V_IDPRODVENT", typeof(decimal));
    
            var v_RUTMECANICOParameter = v_RUTMECANICO != null ?
                new ObjectParameter("V_RUTMECANICO", v_RUTMECANICO) :
                new ObjectParameter("V_RUTMECANICO", typeof(string));
    
            var v_NOMMECParameter = v_NOMMEC != null ?
                new ObjectParameter("V_NOMMEC", v_NOMMEC) :
                new ObjectParameter("V_NOMMEC", typeof(string));
    
            var v_CODPRODUCTOParameter = v_CODPRODUCTO.HasValue ?
                new ObjectParameter("V_CODPRODUCTO", v_CODPRODUCTO) :
                new ObjectParameter("V_CODPRODUCTO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_SERVICIO", v_RUTUSUARIOParameter, v_NOMAPUSUARIOParameter, v_PATENTEParameter, v_IDTIPOSERVParameter, v_IDPRODVENTParameter, v_RUTMECANICOParameter, v_NOMMECParameter, v_CODPRODUCTOParameter);
        }
    
        public virtual int SP_CREATE_USUARIO(string v_RUTUSUARIO, string v_NOMAPUSUARIO, string v_CORREO, string v_PASWD, Nullable<decimal> v_IDROL, string v_DIRECCIONUSUARIO, string v_TELEFONOUSUARIO)
        {
            var v_RUTUSUARIOParameter = v_RUTUSUARIO != null ?
                new ObjectParameter("V_RUTUSUARIO", v_RUTUSUARIO) :
                new ObjectParameter("V_RUTUSUARIO", typeof(string));
    
            var v_NOMAPUSUARIOParameter = v_NOMAPUSUARIO != null ?
                new ObjectParameter("V_NOMAPUSUARIO", v_NOMAPUSUARIO) :
                new ObjectParameter("V_NOMAPUSUARIO", typeof(string));
    
            var v_CORREOParameter = v_CORREO != null ?
                new ObjectParameter("V_CORREO", v_CORREO) :
                new ObjectParameter("V_CORREO", typeof(string));
    
            var v_PASWDParameter = v_PASWD != null ?
                new ObjectParameter("V_PASWD", v_PASWD) :
                new ObjectParameter("V_PASWD", typeof(string));
    
            var v_IDROLParameter = v_IDROL.HasValue ?
                new ObjectParameter("V_IDROL", v_IDROL) :
                new ObjectParameter("V_IDROL", typeof(decimal));
    
            var v_DIRECCIONUSUARIOParameter = v_DIRECCIONUSUARIO != null ?
                new ObjectParameter("V_DIRECCIONUSUARIO", v_DIRECCIONUSUARIO) :
                new ObjectParameter("V_DIRECCIONUSUARIO", typeof(string));
    
            var v_TELEFONOUSUARIOParameter = v_TELEFONOUSUARIO != null ?
                new ObjectParameter("V_TELEFONOUSUARIO", v_TELEFONOUSUARIO) :
                new ObjectParameter("V_TELEFONOUSUARIO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_USUARIO", v_RUTUSUARIOParameter, v_NOMAPUSUARIOParameter, v_CORREOParameter, v_PASWDParameter, v_IDROLParameter, v_DIRECCIONUSUARIOParameter, v_TELEFONOUSUARIOParameter);
        }
    
        public virtual int SP_CREATE_VEHICULO(string v_PATENTE, string v_RUTUSUARIO, string v_MARCA, string v_MODELO, Nullable<decimal> v_ANIO)
        {
            var v_PATENTEParameter = v_PATENTE != null ?
                new ObjectParameter("V_PATENTE", v_PATENTE) :
                new ObjectParameter("V_PATENTE", typeof(string));
    
            var v_RUTUSUARIOParameter = v_RUTUSUARIO != null ?
                new ObjectParameter("V_RUTUSUARIO", v_RUTUSUARIO) :
                new ObjectParameter("V_RUTUSUARIO", typeof(string));
    
            var v_MARCAParameter = v_MARCA != null ?
                new ObjectParameter("V_MARCA", v_MARCA) :
                new ObjectParameter("V_MARCA", typeof(string));
    
            var v_MODELOParameter = v_MODELO != null ?
                new ObjectParameter("V_MODELO", v_MODELO) :
                new ObjectParameter("V_MODELO", typeof(string));
    
            var v_ANIOParameter = v_ANIO.HasValue ?
                new ObjectParameter("V_ANIO", v_ANIO) :
                new ObjectParameter("V_ANIO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_VEHICULO", v_PATENTEParameter, v_RUTUSUARIOParameter, v_MARCAParameter, v_MODELOParameter, v_ANIOParameter);
        }
    
        public virtual int SP_CREATE_VPRODUCTO(Nullable<decimal> v_IDPRODUCTO, Nullable<decimal> v_CANTIDAD, Nullable<decimal> v_CODPRODUCTO)
        {
            var v_IDPRODUCTOParameter = v_IDPRODUCTO.HasValue ?
                new ObjectParameter("V_IDPRODUCTO", v_IDPRODUCTO) :
                new ObjectParameter("V_IDPRODUCTO", typeof(decimal));
    
            var v_CANTIDADParameter = v_CANTIDAD.HasValue ?
                new ObjectParameter("V_CANTIDAD", v_CANTIDAD) :
                new ObjectParameter("V_CANTIDAD", typeof(decimal));
    
            var v_CODPRODUCTOParameter = v_CODPRODUCTO.HasValue ?
                new ObjectParameter("V_CODPRODUCTO", v_CODPRODUCTO) :
                new ObjectParameter("V_CODPRODUCTO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_VPRODUCTO", v_IDPRODUCTOParameter, v_CANTIDADParameter, v_CODPRODUCTOParameter);
        }
    
        public virtual int SP_DELETE_DOCTRIB(Nullable<decimal> v_IDDOCTRIB)
        {
            var v_IDDOCTRIBParameter = v_IDDOCTRIB.HasValue ?
                new ObjectParameter("V_IDDOCTRIB", v_IDDOCTRIB) :
                new ObjectParameter("V_IDDOCTRIB", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_DOCTRIB", v_IDDOCTRIBParameter);
        }
    
        public virtual int SP_DELETE_ODC(Nullable<decimal> v_IDORDEN)
        {
            var v_IDORDENParameter = v_IDORDEN.HasValue ?
                new ObjectParameter("V_IDORDEN", v_IDORDEN) :
                new ObjectParameter("V_IDORDEN", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_ODC", v_IDORDENParameter);
        }
    
        public virtual int SP_DELETE_PRODUCTO(Nullable<decimal> v_IDPRODUCTO)
        {
            var v_IDPRODUCTOParameter = v_IDPRODUCTO.HasValue ?
                new ObjectParameter("V_IDPRODUCTO", v_IDPRODUCTO) :
                new ObjectParameter("V_IDPRODUCTO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_PRODUCTO", v_IDPRODUCTOParameter);
        }
    
        public virtual int SP_DELETE_PROVEEDOR(Nullable<decimal> v_IDPROVEEDOR)
        {
            var v_IDPROVEEDORParameter = v_IDPROVEEDOR.HasValue ?
                new ObjectParameter("V_IDPROVEEDOR", v_IDPROVEEDOR) :
                new ObjectParameter("V_IDPROVEEDOR", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_PROVEEDOR", v_IDPROVEEDORParameter);
        }
    
        public virtual int SP_DELETE_RECEPCION(Nullable<decimal> v_IDRECEPCION)
        {
            var v_IDRECEPCIONParameter = v_IDRECEPCION.HasValue ?
                new ObjectParameter("V_IDRECEPCION", v_IDRECEPCION) :
                new ObjectParameter("V_IDRECEPCION", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_RECEPCION", v_IDRECEPCIONParameter);
        }
    
        public virtual int SP_DELETE_RESERVAS(Nullable<decimal> v_IDRESERVAS)
        {
            var v_IDRESERVASParameter = v_IDRESERVAS.HasValue ?
                new ObjectParameter("V_IDRESERVAS", v_IDRESERVAS) :
                new ObjectParameter("V_IDRESERVAS", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_RESERVAS", v_IDRESERVASParameter);
        }
    
        public virtual int SP_DELETE_RUBRO(Nullable<decimal> v_IDRUBRO)
        {
            var v_IDRUBROParameter = v_IDRUBRO.HasValue ?
                new ObjectParameter("V_IDRUBRO", v_IDRUBRO) :
                new ObjectParameter("V_IDRUBRO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_RUBRO", v_IDRUBROParameter);
        }
    
        public virtual int SP_DELETE_SERVICIO(Nullable<decimal> v_IDSERVICIO)
        {
            var v_IDSERVICIOParameter = v_IDSERVICIO.HasValue ?
                new ObjectParameter("V_IDSERVICIO", v_IDSERVICIO) :
                new ObjectParameter("V_IDSERVICIO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_SERVICIO", v_IDSERVICIOParameter);
        }
    
        public virtual int SP_DELETE_USER(string v_RUTUSUARIO)
        {
            var v_RUTUSUARIOParameter = v_RUTUSUARIO != null ?
                new ObjectParameter("V_RUTUSUARIO", v_RUTUSUARIO) :
                new ObjectParameter("V_RUTUSUARIO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_USER", v_RUTUSUARIOParameter);
        }
    
        public virtual int SP_DELETE_VEHICULO(string v_PATENTE)
        {
            var v_PATENTEParameter = v_PATENTE != null ?
                new ObjectParameter("V_PATENTE", v_PATENTE) :
                new ObjectParameter("V_PATENTE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_VEHICULO", v_PATENTEParameter);
        }
    
        public virtual int SP_DELETE_VPRODUCTO(Nullable<decimal> v_IDPRODVENTA)
        {
            var v_IDPRODVENTAParameter = v_IDPRODVENTA.HasValue ?
                new ObjectParameter("V_IDPRODVENTA", v_IDPRODVENTA) :
                new ObjectParameter("V_IDPRODVENTA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_VPRODUCTO", v_IDPRODVENTAParameter);
        }
    
        public virtual int SP_UPDATE_DOCTRIB(Nullable<decimal> v_IDDOCTRIB, Nullable<System.DateTime> v_FECHACREA, Nullable<decimal> v_IDTIPODOC, Nullable<decimal> v_IDSERVICIO, string v_RUTUSUARIO, Nullable<decimal> v_IDFORMAPAGO, string v_NOMCLIENTE, string v_RUTCLIENTE, Nullable<decimal> v_TOTALPAGAR)
        {
            var v_IDDOCTRIBParameter = v_IDDOCTRIB.HasValue ?
                new ObjectParameter("V_IDDOCTRIB", v_IDDOCTRIB) :
                new ObjectParameter("V_IDDOCTRIB", typeof(decimal));
    
            var v_FECHACREAParameter = v_FECHACREA.HasValue ?
                new ObjectParameter("V_FECHACREA", v_FECHACREA) :
                new ObjectParameter("V_FECHACREA", typeof(System.DateTime));
    
            var v_IDTIPODOCParameter = v_IDTIPODOC.HasValue ?
                new ObjectParameter("V_IDTIPODOC", v_IDTIPODOC) :
                new ObjectParameter("V_IDTIPODOC", typeof(decimal));
    
            var v_IDSERVICIOParameter = v_IDSERVICIO.HasValue ?
                new ObjectParameter("V_IDSERVICIO", v_IDSERVICIO) :
                new ObjectParameter("V_IDSERVICIO", typeof(decimal));
    
            var v_RUTUSUARIOParameter = v_RUTUSUARIO != null ?
                new ObjectParameter("V_RUTUSUARIO", v_RUTUSUARIO) :
                new ObjectParameter("V_RUTUSUARIO", typeof(string));
    
            var v_IDFORMAPAGOParameter = v_IDFORMAPAGO.HasValue ?
                new ObjectParameter("V_IDFORMAPAGO", v_IDFORMAPAGO) :
                new ObjectParameter("V_IDFORMAPAGO", typeof(decimal));
    
            var v_NOMCLIENTEParameter = v_NOMCLIENTE != null ?
                new ObjectParameter("V_NOMCLIENTE", v_NOMCLIENTE) :
                new ObjectParameter("V_NOMCLIENTE", typeof(string));
    
            var v_RUTCLIENTEParameter = v_RUTCLIENTE != null ?
                new ObjectParameter("V_RUTCLIENTE", v_RUTCLIENTE) :
                new ObjectParameter("V_RUTCLIENTE", typeof(string));
    
            var v_TOTALPAGARParameter = v_TOTALPAGAR.HasValue ?
                new ObjectParameter("V_TOTALPAGAR", v_TOTALPAGAR) :
                new ObjectParameter("V_TOTALPAGAR", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_DOCTRIB", v_IDDOCTRIBParameter, v_FECHACREAParameter, v_IDTIPODOCParameter, v_IDSERVICIOParameter, v_RUTUSUARIOParameter, v_IDFORMAPAGOParameter, v_NOMCLIENTEParameter, v_RUTCLIENTEParameter, v_TOTALPAGARParameter);
        }
    
        public virtual int SP_UPDATE_ODC(Nullable<decimal> v_IDORDEN, string v_RUTUSUARIO, Nullable<decimal> v_IDPRODUCTO, Nullable<System.DateTime> v_FECHACREACION, Nullable<decimal> v_IDESTADOORDEN, Nullable<decimal> v_MONTO)
        {
            var v_IDORDENParameter = v_IDORDEN.HasValue ?
                new ObjectParameter("V_IDORDEN", v_IDORDEN) :
                new ObjectParameter("V_IDORDEN", typeof(decimal));
    
            var v_RUTUSUARIOParameter = v_RUTUSUARIO != null ?
                new ObjectParameter("V_RUTUSUARIO", v_RUTUSUARIO) :
                new ObjectParameter("V_RUTUSUARIO", typeof(string));
    
            var v_IDPRODUCTOParameter = v_IDPRODUCTO.HasValue ?
                new ObjectParameter("V_IDPRODUCTO", v_IDPRODUCTO) :
                new ObjectParameter("V_IDPRODUCTO", typeof(decimal));
    
            var v_FECHACREACIONParameter = v_FECHACREACION.HasValue ?
                new ObjectParameter("V_FECHACREACION", v_FECHACREACION) :
                new ObjectParameter("V_FECHACREACION", typeof(System.DateTime));
    
            var v_IDESTADOORDENParameter = v_IDESTADOORDEN.HasValue ?
                new ObjectParameter("V_IDESTADOORDEN", v_IDESTADOORDEN) :
                new ObjectParameter("V_IDESTADOORDEN", typeof(decimal));
    
            var v_MONTOParameter = v_MONTO.HasValue ?
                new ObjectParameter("V_MONTO", v_MONTO) :
                new ObjectParameter("V_MONTO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_ODC", v_IDORDENParameter, v_RUTUSUARIOParameter, v_IDPRODUCTOParameter, v_FECHACREACIONParameter, v_IDESTADOORDENParameter, v_MONTOParameter);
        }
    
        public virtual int SP_UPDATE_PRODUCTO(Nullable<decimal> v_IDPRODUCTO, Nullable<decimal> v_CODUSUARIO, Nullable<decimal> v_IDPROVEEDOR, Nullable<decimal> v_IDTIPOPROD, string v_NOMBREPROD, string v_MARCAPROD, string v_DESCPROD, Nullable<System.DateTime> v_FECHAVENC, Nullable<decimal> v_PRECIOVENTA, Nullable<decimal> v_PRECIOCOMPRA, Nullable<decimal> v_STOCK)
        {
            var v_IDPRODUCTOParameter = v_IDPRODUCTO.HasValue ?
                new ObjectParameter("V_IDPRODUCTO", v_IDPRODUCTO) :
                new ObjectParameter("V_IDPRODUCTO", typeof(decimal));
    
            var v_CODUSUARIOParameter = v_CODUSUARIO.HasValue ?
                new ObjectParameter("V_CODUSUARIO", v_CODUSUARIO) :
                new ObjectParameter("V_CODUSUARIO", typeof(decimal));
    
            var v_IDPROVEEDORParameter = v_IDPROVEEDOR.HasValue ?
                new ObjectParameter("V_IDPROVEEDOR", v_IDPROVEEDOR) :
                new ObjectParameter("V_IDPROVEEDOR", typeof(decimal));
    
            var v_IDTIPOPRODParameter = v_IDTIPOPROD.HasValue ?
                new ObjectParameter("V_IDTIPOPROD", v_IDTIPOPROD) :
                new ObjectParameter("V_IDTIPOPROD", typeof(decimal));
    
            var v_NOMBREPRODParameter = v_NOMBREPROD != null ?
                new ObjectParameter("V_NOMBREPROD", v_NOMBREPROD) :
                new ObjectParameter("V_NOMBREPROD", typeof(string));
    
            var v_MARCAPRODParameter = v_MARCAPROD != null ?
                new ObjectParameter("V_MARCAPROD", v_MARCAPROD) :
                new ObjectParameter("V_MARCAPROD", typeof(string));
    
            var v_DESCPRODParameter = v_DESCPROD != null ?
                new ObjectParameter("V_DESCPROD", v_DESCPROD) :
                new ObjectParameter("V_DESCPROD", typeof(string));
    
            var v_FECHAVENCParameter = v_FECHAVENC.HasValue ?
                new ObjectParameter("V_FECHAVENC", v_FECHAVENC) :
                new ObjectParameter("V_FECHAVENC", typeof(System.DateTime));
    
            var v_PRECIOVENTAParameter = v_PRECIOVENTA.HasValue ?
                new ObjectParameter("V_PRECIOVENTA", v_PRECIOVENTA) :
                new ObjectParameter("V_PRECIOVENTA", typeof(decimal));
    
            var v_PRECIOCOMPRAParameter = v_PRECIOCOMPRA.HasValue ?
                new ObjectParameter("V_PRECIOCOMPRA", v_PRECIOCOMPRA) :
                new ObjectParameter("V_PRECIOCOMPRA", typeof(decimal));
    
            var v_STOCKParameter = v_STOCK.HasValue ?
                new ObjectParameter("V_STOCK", v_STOCK) :
                new ObjectParameter("V_STOCK", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_PRODUCTO", v_IDPRODUCTOParameter, v_CODUSUARIOParameter, v_IDPROVEEDORParameter, v_IDTIPOPRODParameter, v_NOMBREPRODParameter, v_MARCAPRODParameter, v_DESCPRODParameter, v_FECHAVENCParameter, v_PRECIOVENTAParameter, v_PRECIOCOMPRAParameter, v_STOCKParameter);
        }
    
        public virtual int SP_UPDATE_PROVEEDOR(Nullable<decimal> v_IDPROVEEDOR, string v_RUTEMPRESA, string v_RAZONSOCIAL, string v_DIRECCION, Nullable<decimal> v_IDRUBRO, string v_TELEFONOCONTACTO, string v_CORREOCONTACTO)
        {
            var v_IDPROVEEDORParameter = v_IDPROVEEDOR.HasValue ?
                new ObjectParameter("V_IDPROVEEDOR", v_IDPROVEEDOR) :
                new ObjectParameter("V_IDPROVEEDOR", typeof(decimal));
    
            var v_RUTEMPRESAParameter = v_RUTEMPRESA != null ?
                new ObjectParameter("V_RUTEMPRESA", v_RUTEMPRESA) :
                new ObjectParameter("V_RUTEMPRESA", typeof(string));
    
            var v_RAZONSOCIALParameter = v_RAZONSOCIAL != null ?
                new ObjectParameter("V_RAZONSOCIAL", v_RAZONSOCIAL) :
                new ObjectParameter("V_RAZONSOCIAL", typeof(string));
    
            var v_DIRECCIONParameter = v_DIRECCION != null ?
                new ObjectParameter("V_DIRECCION", v_DIRECCION) :
                new ObjectParameter("V_DIRECCION", typeof(string));
    
            var v_IDRUBROParameter = v_IDRUBRO.HasValue ?
                new ObjectParameter("V_IDRUBRO", v_IDRUBRO) :
                new ObjectParameter("V_IDRUBRO", typeof(decimal));
    
            var v_TELEFONOCONTACTOParameter = v_TELEFONOCONTACTO != null ?
                new ObjectParameter("V_TELEFONOCONTACTO", v_TELEFONOCONTACTO) :
                new ObjectParameter("V_TELEFONOCONTACTO", typeof(string));
    
            var v_CORREOCONTACTOParameter = v_CORREOCONTACTO != null ?
                new ObjectParameter("V_CORREOCONTACTO", v_CORREOCONTACTO) :
                new ObjectParameter("V_CORREOCONTACTO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_PROVEEDOR", v_IDPROVEEDORParameter, v_RUTEMPRESAParameter, v_RAZONSOCIALParameter, v_DIRECCIONParameter, v_IDRUBROParameter, v_TELEFONOCONTACTOParameter, v_CORREOCONTACTOParameter);
        }
    
        public virtual int SP_UPDATE_RECEPCION(Nullable<decimal> v_IDRECEPCION, string v_RUTUSUARIO, Nullable<System.DateTime> v_FECHARECEP, string v_OBSERVACIONES, Nullable<decimal> v_IDORDENCOMPRA)
        {
            var v_IDRECEPCIONParameter = v_IDRECEPCION.HasValue ?
                new ObjectParameter("V_IDRECEPCION", v_IDRECEPCION) :
                new ObjectParameter("V_IDRECEPCION", typeof(decimal));
    
            var v_RUTUSUARIOParameter = v_RUTUSUARIO != null ?
                new ObjectParameter("V_RUTUSUARIO", v_RUTUSUARIO) :
                new ObjectParameter("V_RUTUSUARIO", typeof(string));
    
            var v_FECHARECEPParameter = v_FECHARECEP.HasValue ?
                new ObjectParameter("V_FECHARECEP", v_FECHARECEP) :
                new ObjectParameter("V_FECHARECEP", typeof(System.DateTime));
    
            var v_OBSERVACIONESParameter = v_OBSERVACIONES != null ?
                new ObjectParameter("V_OBSERVACIONES", v_OBSERVACIONES) :
                new ObjectParameter("V_OBSERVACIONES", typeof(string));
    
            var v_IDORDENCOMPRAParameter = v_IDORDENCOMPRA.HasValue ?
                new ObjectParameter("V_IDORDENCOMPRA", v_IDORDENCOMPRA) :
                new ObjectParameter("V_IDORDENCOMPRA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_RECEPCION", v_IDRECEPCIONParameter, v_RUTUSUARIOParameter, v_FECHARECEPParameter, v_OBSERVACIONESParameter, v_IDORDENCOMPRAParameter);
        }
    
        public virtual int SP_UPDATE_RESERVAS(Nullable<decimal> v_IDRESERVAS, Nullable<System.DateTime> v_FECHARESERVA, string v_RUTUSUARIO, string v_NOMBRECLIE, string v_CORREOUSU, string v_PATENTE, Nullable<decimal> v_IDTIPOSERVICIO)
        {
            var v_IDRESERVASParameter = v_IDRESERVAS.HasValue ?
                new ObjectParameter("V_IDRESERVAS", v_IDRESERVAS) :
                new ObjectParameter("V_IDRESERVAS", typeof(decimal));
    
            var v_FECHARESERVAParameter = v_FECHARESERVA.HasValue ?
                new ObjectParameter("V_FECHARESERVA", v_FECHARESERVA) :
                new ObjectParameter("V_FECHARESERVA", typeof(System.DateTime));
    
            var v_RUTUSUARIOParameter = v_RUTUSUARIO != null ?
                new ObjectParameter("V_RUTUSUARIO", v_RUTUSUARIO) :
                new ObjectParameter("V_RUTUSUARIO", typeof(string));
    
            var v_NOMBRECLIEParameter = v_NOMBRECLIE != null ?
                new ObjectParameter("V_NOMBRECLIE", v_NOMBRECLIE) :
                new ObjectParameter("V_NOMBRECLIE", typeof(string));
    
            var v_CORREOUSUParameter = v_CORREOUSU != null ?
                new ObjectParameter("V_CORREOUSU", v_CORREOUSU) :
                new ObjectParameter("V_CORREOUSU", typeof(string));
    
            var v_PATENTEParameter = v_PATENTE != null ?
                new ObjectParameter("V_PATENTE", v_PATENTE) :
                new ObjectParameter("V_PATENTE", typeof(string));
    
            var v_IDTIPOSERVICIOParameter = v_IDTIPOSERVICIO.HasValue ?
                new ObjectParameter("V_IDTIPOSERVICIO", v_IDTIPOSERVICIO) :
                new ObjectParameter("V_IDTIPOSERVICIO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_RESERVAS", v_IDRESERVASParameter, v_FECHARESERVAParameter, v_RUTUSUARIOParameter, v_NOMBRECLIEParameter, v_CORREOUSUParameter, v_PATENTEParameter, v_IDTIPOSERVICIOParameter);
        }
    
        public virtual int SP_UPDATE_RUBRO(Nullable<decimal> v_IDRUBRO, string v_DESCRUBRO)
        {
            var v_IDRUBROParameter = v_IDRUBRO.HasValue ?
                new ObjectParameter("V_IDRUBRO", v_IDRUBRO) :
                new ObjectParameter("V_IDRUBRO", typeof(decimal));
    
            var v_DESCRUBROParameter = v_DESCRUBRO != null ?
                new ObjectParameter("V_DESCRUBRO", v_DESCRUBRO) :
                new ObjectParameter("V_DESCRUBRO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_RUBRO", v_IDRUBROParameter, v_DESCRUBROParameter);
        }
    
        public virtual int SP_UPDATE_SERVICIO(Nullable<decimal> v_IDSERVICIO, string v_RUTUSUARIO, string v_NOMAPUSUARIO, string v_PATENTE, Nullable<decimal> v_IDTIPOSERV, Nullable<decimal> v_IDPRODVENT, string v_RUTMECANICO, string v_NOMMEC, Nullable<decimal> v_CODPRODUCTO)
        {
            var v_IDSERVICIOParameter = v_IDSERVICIO.HasValue ?
                new ObjectParameter("V_IDSERVICIO", v_IDSERVICIO) :
                new ObjectParameter("V_IDSERVICIO", typeof(decimal));
    
            var v_RUTUSUARIOParameter = v_RUTUSUARIO != null ?
                new ObjectParameter("V_RUTUSUARIO", v_RUTUSUARIO) :
                new ObjectParameter("V_RUTUSUARIO", typeof(string));
    
            var v_NOMAPUSUARIOParameter = v_NOMAPUSUARIO != null ?
                new ObjectParameter("V_NOMAPUSUARIO", v_NOMAPUSUARIO) :
                new ObjectParameter("V_NOMAPUSUARIO", typeof(string));
    
            var v_PATENTEParameter = v_PATENTE != null ?
                new ObjectParameter("V_PATENTE", v_PATENTE) :
                new ObjectParameter("V_PATENTE", typeof(string));
    
            var v_IDTIPOSERVParameter = v_IDTIPOSERV.HasValue ?
                new ObjectParameter("V_IDTIPOSERV", v_IDTIPOSERV) :
                new ObjectParameter("V_IDTIPOSERV", typeof(decimal));
    
            var v_IDPRODVENTParameter = v_IDPRODVENT.HasValue ?
                new ObjectParameter("V_IDPRODVENT", v_IDPRODVENT) :
                new ObjectParameter("V_IDPRODVENT", typeof(decimal));
    
            var v_RUTMECANICOParameter = v_RUTMECANICO != null ?
                new ObjectParameter("V_RUTMECANICO", v_RUTMECANICO) :
                new ObjectParameter("V_RUTMECANICO", typeof(string));
    
            var v_NOMMECParameter = v_NOMMEC != null ?
                new ObjectParameter("V_NOMMEC", v_NOMMEC) :
                new ObjectParameter("V_NOMMEC", typeof(string));
    
            var v_CODPRODUCTOParameter = v_CODPRODUCTO.HasValue ?
                new ObjectParameter("V_CODPRODUCTO", v_CODPRODUCTO) :
                new ObjectParameter("V_CODPRODUCTO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_SERVICIO", v_IDSERVICIOParameter, v_RUTUSUARIOParameter, v_NOMAPUSUARIOParameter, v_PATENTEParameter, v_IDTIPOSERVParameter, v_IDPRODVENTParameter, v_RUTMECANICOParameter, v_NOMMECParameter, v_CODPRODUCTOParameter);
        }
    
        public virtual int SP_UPDATE_USUARIO(string v_RUTUSUARIO, string v_NOMBREUSUARIO, string v_CORREO, string v_PASWD, Nullable<decimal> v_IDROL, string v_DIRECCIONUSUARIO, string v_TELEFONOUSUARIO)
        {
            var v_RUTUSUARIOParameter = v_RUTUSUARIO != null ?
                new ObjectParameter("V_RUTUSUARIO", v_RUTUSUARIO) :
                new ObjectParameter("V_RUTUSUARIO", typeof(string));
    
            var v_NOMBREUSUARIOParameter = v_NOMBREUSUARIO != null ?
                new ObjectParameter("V_NOMBREUSUARIO", v_NOMBREUSUARIO) :
                new ObjectParameter("V_NOMBREUSUARIO", typeof(string));
    
            var v_CORREOParameter = v_CORREO != null ?
                new ObjectParameter("V_CORREO", v_CORREO) :
                new ObjectParameter("V_CORREO", typeof(string));
    
            var v_PASWDParameter = v_PASWD != null ?
                new ObjectParameter("V_PASWD", v_PASWD) :
                new ObjectParameter("V_PASWD", typeof(string));
    
            var v_IDROLParameter = v_IDROL.HasValue ?
                new ObjectParameter("V_IDROL", v_IDROL) :
                new ObjectParameter("V_IDROL", typeof(decimal));
    
            var v_DIRECCIONUSUARIOParameter = v_DIRECCIONUSUARIO != null ?
                new ObjectParameter("V_DIRECCIONUSUARIO", v_DIRECCIONUSUARIO) :
                new ObjectParameter("V_DIRECCIONUSUARIO", typeof(string));
    
            var v_TELEFONOUSUARIOParameter = v_TELEFONOUSUARIO != null ?
                new ObjectParameter("V_TELEFONOUSUARIO", v_TELEFONOUSUARIO) :
                new ObjectParameter("V_TELEFONOUSUARIO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_USUARIO", v_RUTUSUARIOParameter, v_NOMBREUSUARIOParameter, v_CORREOParameter, v_PASWDParameter, v_IDROLParameter, v_DIRECCIONUSUARIOParameter, v_TELEFONOUSUARIOParameter);
        }
    
        public virtual int SP_UPDATE_VEHICULO(string v_PATENTE, string v_RUTUSUARIO, string v_MARCA, string v_MODELO, Nullable<decimal> v_ANIO)
        {
            var v_PATENTEParameter = v_PATENTE != null ?
                new ObjectParameter("V_PATENTE", v_PATENTE) :
                new ObjectParameter("V_PATENTE", typeof(string));
    
            var v_RUTUSUARIOParameter = v_RUTUSUARIO != null ?
                new ObjectParameter("V_RUTUSUARIO", v_RUTUSUARIO) :
                new ObjectParameter("V_RUTUSUARIO", typeof(string));
    
            var v_MARCAParameter = v_MARCA != null ?
                new ObjectParameter("V_MARCA", v_MARCA) :
                new ObjectParameter("V_MARCA", typeof(string));
    
            var v_MODELOParameter = v_MODELO != null ?
                new ObjectParameter("V_MODELO", v_MODELO) :
                new ObjectParameter("V_MODELO", typeof(string));
    
            var v_ANIOParameter = v_ANIO.HasValue ?
                new ObjectParameter("V_ANIO", v_ANIO) :
                new ObjectParameter("V_ANIO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_VEHICULO", v_PATENTEParameter, v_RUTUSUARIOParameter, v_MARCAParameter, v_MODELOParameter, v_ANIOParameter);
        }
    
        public virtual int SP_UPDATE_VPRODUCTO(Nullable<decimal> v_IDPRODVENTA, Nullable<decimal> v_IDPRODUCTO, Nullable<decimal> v_CANTIDAD, Nullable<decimal> v_CODPRODUCTO)
        {
            var v_IDPRODVENTAParameter = v_IDPRODVENTA.HasValue ?
                new ObjectParameter("V_IDPRODVENTA", v_IDPRODVENTA) :
                new ObjectParameter("V_IDPRODVENTA", typeof(decimal));
    
            var v_IDPRODUCTOParameter = v_IDPRODUCTO.HasValue ?
                new ObjectParameter("V_IDPRODUCTO", v_IDPRODUCTO) :
                new ObjectParameter("V_IDPRODUCTO", typeof(decimal));
    
            var v_CANTIDADParameter = v_CANTIDAD.HasValue ?
                new ObjectParameter("V_CANTIDAD", v_CANTIDAD) :
                new ObjectParameter("V_CANTIDAD", typeof(decimal));
    
            var v_CODPRODUCTOParameter = v_CODPRODUCTO.HasValue ?
                new ObjectParameter("V_CODPRODUCTO", v_CODPRODUCTO) :
                new ObjectParameter("V_CODPRODUCTO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_VPRODUCTO", v_IDPRODVENTAParameter, v_IDPRODUCTOParameter, v_CANTIDADParameter, v_CODPRODUCTOParameter);
        }
    }
}
