//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiExpressV3.datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_SERVICIO
    {
        public TIPO_SERVICIO()
        {
            this.RESERVAS = new HashSet<RESERVAS>();
            this.SERVICIO = new HashSet<SERVICIO>();
        }
    
        public decimal ID_TIPO_SERVICIO { get; set; }
        public string DESCRIPCION_TIPO_SERV { get; set; }
        public decimal PRECIO { get; set; }
    
        public virtual ICollection<RESERVAS> RESERVAS { get; set; }
        public virtual ICollection<SERVICIO> SERVICIO { get; set; }
    }
}
