//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiExpressV3.datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.DOCUMENTO_TRIBUTARIO = new HashSet<DOCUMENTO_TRIBUTARIO>();
            this.ORDEN_DE_COMPRA = new HashSet<ORDEN_DE_COMPRA>();
            this.RESERVAS = new HashSet<RESERVAS>();
            this.VEHICULOS = new HashSet<VEHICULOS>();
        }
    
        public string RUT_USUARIO { get; set; }
        public string NOM_AP_USUARIO { get; set; }
        public string CORREO { get; set; }
        public string PASWD { get; set; }
        public decimal ID_ROL_USUARIO { get; set; }
        public string DIRECCION_USUARIO { get; set; }
        public string TELEFONO_USUARIO { get; set; }
    
        public virtual ICollection<DOCUMENTO_TRIBUTARIO> DOCUMENTO_TRIBUTARIO { get; set; }
        public virtual ICollection<ORDEN_DE_COMPRA> ORDEN_DE_COMPRA { get; set; }
        public virtual ICollection<RESERVAS> RESERVAS { get; set; }
        public virtual ROL_USUARIO ROL_USUARIO { get; set; }
        public virtual ICollection<VEHICULOS> VEHICULOS { get; set; }
    }
}
