//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiExpressV3.datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICULOS
    {
        public VEHICULOS()
        {
            this.RESERVAS = new HashSet<RESERVAS>();
            this.SERVICIO = new HashSet<SERVICIO>();
        }
    
        public string PATENTE { get; set; }
        public string RUT_USUARIO { get; set; }
        public string MARCA { get; set; }
        public string MODELO { get; set; }
        public Nullable<short> ANIO { get; set; }
    
        public virtual ICollection<RESERVAS> RESERVAS { get; set; }
        public virtual ICollection<SERVICIO> SERVICIO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
